package com.ordermanagement.order_api_service.controller;

import com.example.kafka.avro.Order; // This class is auto-generated by avro-maven-plugin
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.UUID;

// DTO for the web request
record OrderRequest(String product, float price) {}

@RestController
@RequiredArgsConstructor
public class OrderProducerController {

    private final KafkaTemplate<String, Order> kafkaTemplate;

    @Value("${app.topics.orders}")
    private String ordersTopic;

    @PostMapping("/order")
    public String sendOrder(@RequestBody OrderRequest request) {
        String orderId = UUID.randomUUID().toString();

        // Build the Avro Order object
        Order order = Order.newBuilder()
                .setOrderId(orderId)
                .setProduct(request.getProduct())
                .setPrice(request.getPrice())
                .build();

        kafkaTemplate.send(ordersTopic, orderId, order);
        
        return "Order " + orderId + " sent.";
    }
}